web/secret_door/chal/challenge/app.py
from blueprints.web_routes import web
from blueprints.api_routes import api
from flask import Flask, render_template, jsonify
from database import mysql

app = Flask(__name__)
app.config.from_object('config.Config')

mysql.init_app(app)

app.register_blueprint(web, url_prefix='/')
app.register_blueprint(api, url_prefix='/api')

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404 

@app.errorhandler(403)
def not_found(error):
    return render_template('403.html'), 403

@app.errorhandler(Exception)
def handle_error(error):
    print(error)
    message = error.description if hasattr(error, 'description') else [str(x) for x in error.args]
    response = {
        'error': {
            'type': error.__class__.__name__,
            'message': message
        }
    }
    error_code = error.code if hasattr(error, 'code') else 500
    return jsonify(response), error_code

web/secret_door/chal/challenge/blueprints/api_routes.py
from flask import Blueprint, request, abort, session, redirect, url_for, jsonify
from util import is_valid_email, verify_password, create_JWT, create_hash, is_authenticated, verify_JWT, escape_html, timestamp
from database import query_db, call_procedure
from datetime import datetime

api = Blueprint('api', __name__)


@api.route('/login', methods=["POST"])
def api_login():
    if not request.is_json:
        return abort(400, 'Invalid POST format!')
    data = request.get_json()
    email = data.get('email', '')
    password = data.get('password', '')
    if not email or not password:
        return abort(401, 'All fields are required')
    query = "SELECT * FROM users WHERE email = %s"
    user = query_db(query, (email,), one=True)
    if user:
        password_check = verify_password(user['password'], password)
        if password_check:
            token = create_JWT(user['email'], user['role'])
            session['auth'] = token
            return redirect(url_for('web.home'))
        else:
            return abort(401, 'Invalid Credential')
    else:
        return abort(401, 'Invalid Credential')


@api.route('/register', methods=["POST"])
def api_register():
    if not request.is_json:
        return abort(400, 'Invalid POST format!')
    data = request.get_json()
    email = data.get('email', '')
    password = data.get('password', '')
    if not email or not password:
        return abort(401, 'All fields are required')
    if not is_valid_email(email):
        return abort(401, 'Invalid Email')
    hashed_password = create_hash(password)
    try:
        call_procedure("insert_user", (email, hashed_password))
        return redirect(url_for('web.login'))
    except Exception as e:
        return abort(500, 'Registration failed - some error occurred')


@api.route('/update-email', methods=["POST"])
@is_authenticated
def update_email():
    if not request.is_json:
        return abort(400, 'Invalid POST format!')
    data = request.get_json()
    new_email = data.get('email', '')
    if not is_valid_email(new_email):
        return abort(401, 'Invalid Email')
    # Get old email address
    token = session.get('auth')
    decoded_token = verify_JWT(token)
    old_email = decoded_token["email"]
    # Logging Data
    time = datetime.now()
    update_date = time.strftime("%Y-%m-%d %H:%M:%S")
    log_text = f"Email updated to {new_email} at {update_date}"
    log_text = log_text.format(new_email=new_email, timestamp=timestamp, update_date=update_date)
    # Update users
    call_procedure("update_user_email", (old_email, new_email))
    # Insert Logs
    log_text = escape_html(log_text)
    call_procedure("insert_log", (new_email, log_text))
    # Log out of the page
    session['auth'] = None
    return redirect(url_for('web.logout'))


@api.route('/view-logs', methods=["GET"])
@is_authenticated
def view_logs():
    # Get email from JWT token
    token = session.get('auth')
    decoded_token = verify_JWT(token)
    email = decoded_token["email"]

    user_query = "SELECT id FROM users WHERE email = %s"
    user = query_db(user_query, (email,), one=True)
    log_query = "SELECT log_text, log_date FROM logs WHERE user_id = %s ORDER BY log_date DESC"
    logs = query_db(log_query, (user['id'],), one=False)
    return jsonify(logs)

web/secret_door/chal/challenge/blueprints/web_routes.py
from util import is_authenticated, is_admin
from flask import Blueprint, render_template, session, redirect, url_for, current_app

web = Blueprint('web', __name__)

@web.route('/')
def login():
    session['auth'] = None
    return render_template('login.html')

@web.route('/register')
def web_register():
    session['auth'] = None
    return render_template('register.html')

@web.route('/logout')
def logout():
    session['auth'] = None
    return redirect(url_for('web.login'))

@web.route('/home')
@is_authenticated
def home():
    return render_template('home.html')

@web.route('/update-email')
@is_authenticated
def web_update_email():
    return render_template('update-email.html')

@web.route('/update-logs')
@is_authenticated
def web_view_personal_logs():
    return render_template('personal-logs.html')

@web.route('/admin')
@is_admin
def admin_home():
    flag = current_app.config['FLAG']
    return render_template('admin.html', flag=flag)

web/secret_door/chal/challenge/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
</head>
<body>
    <h1>Admin Page</h1>
    {% if flag %}
        <p>The flag: {{ flag }}</p>
    {% else %}
        <p>The flag is disabled.</p>
    {% endif %}
</body>
</html>

web/secret_door/chal/challenge/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Secret Door - {% block pageTitle %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('web.home') }}">DOOR</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% if session.get('auth') %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('web.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('web.web_update_email') }}"
                >Update Email</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="{{ url_for('web.web_view_personal_logs') }}"
                >View Logs</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('web.logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('web.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('web.web_register') }}"
                >Register</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

web/secret_door/chal/challenge/templates/login.html
{% extends "base.html" %} {% block pageTitle %}Login{% endblock %} {% block
content %}
<div class="container">
  <h1>Login</h1>
  <form id="login-form">
    <div class="form-group">
      <label for="email">Email:</label>
      <input class="form-control" type="email" id="email" name="email" required />
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input class="form-control" type="password" id="password" name="password" required />
    </div>

    <input type="submit" value="Login" class="btn btn-primary" />
  </form>
  <p>Don't have an account? <a href="/register">Register here</a>.</p>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const form = document.getElementById("login-form");

      form.addEventListener("submit", async function (event) {
        event.preventDefault();

        const email = document.getElementById("email").value;
        const password = document.getElementById("password").value;

        try {
          const response = await fetch("/api/login", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ email, password }),
            redirect: "follow",
          });

          if (response.ok) {
            const redirectedUrl = response.url;
            if (redirectedUrl) {
              alert("Login successful!");
              window.location.href = redirectedUrl;
            }
          } else {
            const error = await response.json();
            alert("Login failed: " + error.message);
          }
        } catch (error) {
          console.log(error);
          alert("An error occurred: " + error.message);
        }
      });
    });
  </script>
</div>
{% endblock %}

web/secret_door/chal/challenge/templates/personal-logs.html
{% extends "base.html" %} 

{% block pageTitle %}View Logs{% endblock %}

{% block content %}
<div class="container">
    <h1>User Logs</h1>
    <div id="logs-container">
        Loading logs...
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            fetch('/api/view-logs')
                .then(response => response.json())
                .then(data => {
                    const logsContainer = document.getElementById('logs-container');
                    logsContainer.innerHTML = '';
                    console.log(data)
                    if (data.length === 0) {
                        logsContainer.innerText = 'No logs found.';
                    } else {
                        data.forEach(log => {
                            const logEntry = document.createElement('div');
                            logEntry.className = 'card mb-2 mt-2';
                            logEntry.innerHTML = `
                            <div class="card-body">
                                <div class="text-muted">${log.log_date}</div>
                                <div class="log-text text-truncate">${log.log_text}</div>
                            </div>
                            `;
                            logsContainer.appendChild(logEntry);
                        });
                    }
                })
                .catch(error => {
                    console.error('Error fetching logs:', error);
                    document.getElementById('logs-container').innerHTML = '<p class="no-logs">Error fetching logs.</p>';
                });
        });
    </script>
</div>
{% endblock %}

web/secret_door/chal/challenge/templates/register.html
{% extends "base.html" %}

{% block pageTitle %}Register{% endblock %}

{% block content %}
<div class="container">
    <h1>Register</h1>
    <form id="register-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input class="form-control" type="email" id="email" name="email" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input class="form-control" type="password" id="password" name="password" required>
        </div>

        <input type="submit" value="Register" class="btn btn-primary">
    </form>
    <p>Already have an account? <a href="/">Login here</a>.</p>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const form = document.getElementById('register-form');

            form.addEventListener('submit', async function (event) {
                event.preventDefault();

                const email = document.getElementById('email').value;
                const password = document.getElementById('password').value;

                try {
                    const response = await fetch('/api/register', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ email, password }),
                        redirect: 'follow'
                    });

                    if (response.ok) {

                        const redirectedUrl = response.url;
                        if (redirectedUrl) {
                            alert('Registration successful!');
                            window.location.href = redirectedUrl;
                        }
                    } else {
                        const error = await response.json();
                        alert('Registration failed: ' + error.message);
                    }
                } catch (error) {
                    alert('An error occurred: ');
                }
            });
        });
    </script>
</div>
{% endblock %}

web/secret_door/chal/challenge/templates/update-email.html
{% extends "base.html" %} {% block pageTitle %}Update Email{% endblock %} {%
block content %}
<div class="container">
  <h1>Update Email</h1>
  <form id="update-email-form">
    <div class="form-group">
      <label for="email">New Email:</label>
      <input  class="form-control" type="email" id="email" name="email" required />
    </div>

    <input type="submit" value="Update Email" class="btn btn-primary"/>
  </form>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const form = document.getElementById("update-email-form");

    form.addEventListener("submit", async function (event) {
      event.preventDefault(); // Prevent the default form submission

      const email = document.getElementById("email").value;

      try {
        const response = await fetch("/api/update-email", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ email }),
        });
        const redirectedUrl = response.url;

        if (response.ok) {
          if (redirectedUrl) {
            alert("Email updated successfully!");
            window.location.href = redirectedUrl;
          }
        } else {
          alert("Error updating email");
        }
      } catch (error) {
        alert("An error occurred: " + error.message);
      }
    });
  });
</script>
{% endblock %}